
import Head from "next/head";
import "./globals.css";
import { Montserrat } from "next/font/google";
import FontAwesomeProvider from './FontAwesomeProvider';

const montserrat = Montserrat({
  weight: ["100", "200", "300", "400", "500", "600", "700"],
  style: ["normal", "italic"],
  variable: "--font-montserrat",
  subsets: ["latin"],
  display: "swap",
});


export const metadata = {
  title: 'Akiraverse',
  description: 'Generated by create next app',
}

type PropsLayout = {
  children: React.ReactNode
}

const RootLayout = ({ children }: PropsLayout) => {
	return (
    <html lang="en">
      <Head>
        <script src="https://kit.fontawesome.com/0c3026cdac.js" crossOrigin="anonymous"></script>
      </Head>
      <body className={`${montserrat.variable} ${montserrat.style} bg-gray-900/80 `}>
        <FontAwesomeProvider>
            {children}  
        </FontAwesomeProvider>
      </body>
    </html>
	)
}

export default RootLayout
