import type { Metadata } from "next";
import Head from "next/head";
import "./globals.css";
import Header from "@/components/header";
import MenuList from "./menuList";
import { Poppins } from "next/font/google";
import { ReactNode } from 'react';
import FontAwesomeProvider from './FontAwesomeProvider';

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700"],
  style: ["normal", "italic"],
  variable: "--font-poppins",
  subsets: ["latin"],
  display: "swap",
});


export const metadata = {
  title: 'Akiraverse',
  description: 'Generated by create next app',
}

type PropsLayout = {
  children: React.ReactNode
}

const RootLayout = ({ children }: PropsLayout) => {
	return (
    <html lang="en">
      <Head>
        <script src="https://kit.fontawesome.com/0c3026cdac.js" crossOrigin="anonymous"></script>
      </Head>
      <body className={`${poppins.variable} ${poppins.style} bg-[#1e1e1e]`}>
        <FontAwesomeProvider>
          <Header title="User" id="user" menuList={MenuList}>
            {children}  
          </Header>
        </FontAwesomeProvider>
      </body>
    </html>
	)
}

export default RootLayout
